name: Mobile CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.5.0
          cache: "npm"
          cache-dependency-path: "Mobile/package-lock.json"

      - name: Install dependencies
        working-directory: ./Mobile
        run: npm install

      - name: Run tests
        working-directory: ./Mobile
        run: npx jest --ci

      - name: Run linting
        working-directory: ./Mobile
        run: npm run lint
